"""empty message

Revision ID: 6a29d238724b
Revises: 74a0be016a64
Create Date: 2025-09-20 13:07:36.637361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a29d238724b'
down_revision = '74a0be016a64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('to_do_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('description', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('due_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('priority', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('status', sa.Boolean(), nullable=False))
        batch_op.drop_column('task')
        batch_op.drop_column('check')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('to_do_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('check', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('task', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('status')
        batch_op.drop_column('priority')
        batch_op.drop_column('due_date')
        batch_op.drop_column('description')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
